# Site settings
title: Mauricio Flores Hernandez
description: A blog about lorem ipsum dolor sit amet
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://devmau.me/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mauricio Flores
user_description: My name is Mauricio. I am studying an engineering in information technologies and communications at Tecnológico Nacional de México en Roque. I am currently in seventh semester of my career. Right now i am focused on completing the Github Campus Expert program. Recently some friends and me founded RoqByte, that is a student community to help us each others to improve our software development skills and build amazing projects.
user_title: Software Developer
email: mau1361317@gmail.com
twitter_username: Mau_Hernandez_F
github_username:  devmaufh


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
